### ISSUE TITLE
Possible BetterEnd incompatibility - Crash report "Feature placement"

### ISSUE THREAD

**Issue by piber20** [team-abnormals/endergetic#140] opened 2021-01-16 08:57 UTC
[latest - Copy.log](https://github.com/team-abnormals/endergetic/files/5824082/latest.-.Copy.log)

Blame seems to say the issue is with biome endergetic:poise_forest , hopefully this helps.

I don't recall the mod crashing before installing a few more mods, one of them being BetterEnd (Forge). I tried a new session for testing with BetterEnd disabled, and I wasn't able to reproduce the crash. This could be some kind of compatibility issue between endergetic and betterend.

**Comment by SmellyModder** [comment] 2021-01-16 15:17
I don't see how that could be happening because Puff Bug Hives are a registered configured feature.
BetterEnd may be doing something that's causing this issue, but I can't know for sure without knowing the full details of what they're doing.

**Comment by SmellyModder** [comment] 2021-01-16 15:19
I think it would be best to open an issue over at BetterEnd about this because I'm not sure what they're doing that could cause this.

**Comment by piber20** [comment] 2021-01-16 15:53
ill open an issue for them too. thank you

**Comment by Beethoven92** [comment] 2021-01-16 16:43
I am not able to reproduce this issue with only BetterEnd and Endergetic installed, so it seems not to be a direct incompatibility. That crash report is also very weird, and right now i honestly don't understand how BetterEnd could eventually be causing this, we aren't doing anything particularly weird with world gen and another issue of this kind (even with other world gen mods) was never reported before

**Comment by SmellyModder** [comment] 2021-01-16 18:21
I wasn't able to reproduce it either. I didn't think it was a direct issue caused by BetterEnd, but I wanted to be sure.

**Comment by bageldotjpg** [comment] 2021-02-15 15:47
Closing this for now, re-open if it still occurs and more information is available.

**Closed by bageldotjpg** 2021-02-15 15:47 UTC
Labels: Bug?, Mod Conflict, More Info
