### ISSUE TITLE
Blame error generated during worldgen

### ISSUE THREAD

**Issue by sfiomn** [team-abnormals/endergetic#207] opened 2022-01-30 20:02 UTC
Hello,

I've seen this log in latest.log:

[29Jan2022 16:03:20.440] [main/ERROR] [com.telepathicgrunt.blame.Blame/]: 
** Blame Report Worldgen Import 1.16.5-3.7.0-forge **

 Failed to parse worldgen. This can be tricky to solve but it could be from using a value that is over a hardcoded limit.
 Here's some info to help narrow down where and what could be the broken worldgen element.

 Error msg is: Base value out of range: 256 [-10-128]
 Parent Affected: ResourceKey[minecraft:worldgen/configured_feature / endergetic:corrock_tower] | net.minecraft.world.gen.feature.ConfiguredFeature@6a9be23f

 Partial JSON Result: null

Is this intentional ? Might a silent error, so I share it here :)

**Comment by SmellyModder** [comment] 2022-01-31 20:21
Duplicate of #175

**Closed by SmellyModder** 2022-01-31 20:21 UTC
